import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: '1', name: { en: 'Extracts', ar: 'المستخلصات' }, slug: 'extracts', type: 'b2b' },
  { id: '2', name: { en: 'Ferments', ar: 'المخمرات' }, slug: 'ferments', type: 'b2b' },
  { id: '3', name: { en: 'Oils', ar: 'الزيوت' }, slug: 'oils', type: 'b2b' },
  { id: '4', name: { en: 'Peptides', ar: 'الببتيدات' }, slug: 'peptides', type: 'b2b' },
  { id: '5', name: { en: 'Grow Kits', ar: 'علب النمو' }, slug: 'grow-kits', type: 'b2c' },
  { id: '6', name: { en: 'Lab Supplies', ar: 'لوازم المختبر' }, slug: 'lab-supplies', type: 'b2c' },
];

export const products: Product[] = [
  // ---------------- EXTRACTS ----------------
  {
    id: 'prod_001',
    name: { en: 'Reishi Spore Extract', ar: 'مستخلص فطر الريشي' },
    slug: 'reishi-spore-extract',
    description: {
      en: 'A potent antioxidant powerhouse derived from the revered Reishi mushroom. This extract is known for its ability to combat oxidative stress, reduce inflammation, and promote cellular regeneration for a visibly youthful complexion.',
      ar: 'قوة مضادة للأكسدة مستمدة من فطر الريشي الموقر. يُعرف هذا المستخلص بقدرته على مكافحة الإجهاد التأكسدي وتقليل الالتهابات وتعزيز تجديد الخلايا لبشرة شابة بشكل واضح.',
    },
    price: 8500,
    salePrice: 7500,
    imageUrl: 'https://picsum.photos/seed/101/600/600',
    imageHint: 'cosmetic bottle',
    category: 'Extracts',
    ingredients: { en: ['Ganoderma Lucidum (Reishi) Spore Extract', 'Glycerin', 'Water'], ar: ['مستخلص فطر الريشي (غانوديرما لوسيدوم)', 'غليسرين', 'ماء'] },
    application: { en: 'Apply 2-3 drops to clean skin, morning and night, before moisturizing.', ar: 'ضعي 2-3 قطرات على بشرة نظيفة صباحًا ومساءً قبل الترطيب.' },
    benefits: { en: ['Anti-aging', 'Reduces Inflammation', 'Boosts Hydration'], ar: ['مكافحة الشيخوخة', 'يقلل الالتهاب', 'يعزز الترطيب'] },
    type: 'b2b',
  },
  {
    id: 'prod_005',
    name: { en: 'Shiitake Brightening Complex', ar: 'مركب تفتيح شيتاكي' },
    slug: 'shiitake-brightening-complex',
    description: {
      en: 'A concentrated extract from Shiitake mushrooms, rich in kojic acid. This active is designed to naturally fade hyperpigmentation, even out skin tone, and restore a luminous glow to dull, tired skin.',
      ar: 'مستخلص مركز من فطر شيتاكي، غني بحمض الكوجيك. تم تصميم هذا العنصر النشط لتلاشي فرط التصبغ بشكل طبيعي، وتوحيد لون البشرة، واستعادة إشراقة متوهجة للبشرة الباهتة والمتعبة.',
    },
    price: 7800,
    imageUrl: 'https://picsum.photos/seed/105/600/600',
    imageHint: 'glowing serum',
    category: 'Extracts',
    ingredients: { en: ['Lentinus Edodes (Shiitake) Extract', 'Butylene Glycol', 'Niacinamide'], ar: ['مستخلص فطر شيتاكي', 'بيوتيلين جلايكول', 'نياسيناميد'] },
    application: { en: 'Apply to dark spots or all over the face before moisturizing.', ar: 'يوضع على البقع الداكنة أو على كامل الوجه قبل الترطيب.' },
    benefits: { en: ['Fades Hyperpigmentation', 'Evens Skin Tone', 'Brightening'], ar: ['يلاشي فرط التصبغ', 'يوحد لون البشرة', 'تفتيح'] },
    type: 'b2b',
  },
  {
    id: 'prod_011',
    name: { en: 'Maitake Beta-Glucan Extract', ar: 'مستخلص بيتا جلوكان الميتاكي' },
    slug: 'maitake-beta-glucan-extract',
    description: {
      en: 'High-purity beta-glucans extracted from Maitake mushrooms. It provides an invisible shield against environmental damage while deeply hydrating the skin layers.',
      ar: 'بيتا جلوكان عالي النقاء مستخرج من فطر الميتاكي. يوفر درعاً غير مرئي ضد الأضرار البيئية بينما يرطب طبقات البشرة بعمق.',
    },
    price: 9200,
    imageUrl: 'https://picsum.photos/seed/111/600/600',
    imageHint: 'clear extract liquid',
    category: 'Extracts',
    ingredients: { en: ['Grifola Frondosa (Maitake) Extract', 'Hyaluronic Acid'], ar: ['مستخلص الميتاكي', 'حمض الهيالورونيك'] },
    application: { en: 'Use alone or mix with any facial cream.', ar: 'يستخدم بمفرده أو يمزج مع أي كريم للوجه.' },
    benefits: { en: ['Environmental Shield', 'Deep Hydration'], ar: ['درع بيئي', 'ترطيب عميق'] },
    type: 'b2b',
  },
  {
    id: 'prod_012',
    name: { en: 'Turkey Tail Cellular Extract', ar: 'مستخلص ذيل الديك الرومي الخلوي' },
    slug: 'turkey-tail-cellular-extract',
    description: {
      en: 'Rich in polysaccharides, this cellular extract helps support the structural integrity of the skin, promoting firmness and reducing sagging over time.',
      ar: 'غني بالسكريات المتعددة، يساعد هذا المستخلص الخلوي في دعم البنية الهيكلية للبشرة، مما يعزز الثبات ويقلل الترهل بمرور الوقت.',
    },
    price: 8800,
    salePrice: 8000,
    imageUrl: 'https://picsum.photos/seed/112/600/600',
    imageHint: 'amber glass bottle',
    category: 'Extracts',
    ingredients: { en: ['Trametes Versicolor Extract', 'Vegetable Glycerin'], ar: ['مستخلص تراميتس فيرسيكولور', 'غليسرين نباتي'] },
    application: { en: 'Apply evenly across the face and neck.', ar: 'يوضع بالتساوي على الوجه والرقبة.' },
    benefits: { en: ['Promotes Firmness', 'Reduces Sagging'], ar: ['يعزز التماسك', 'يقلل الترهل'] },
    type: 'b2b',
  },

  // ---------------- FERMENTS ----------------
  {
    id: 'prod_002',
    name: { en: 'Chaga Ferment Filtrate', ar: 'مرشح تخمير الشاجا' },
    slug: 'chaga-ferment-filtrate',
    description: {
      en: 'Harnessing the power of fermented Chaga, this bio-active filtrate is rich in enzymes and beta-glucans. It strengthens the skin\'s microbiome, enhances its natural defense system, and provides deep, lasting hydration.',
      ar: 'يستغل هذا المرشح النشط حيويًا قوة فطر الشاجا المخمر، وهو غني بالإنزيمات والبيتا جلوكان. يقوي ميكروبيوم البشرة، ويعزز نظام دفاعها الطبيعي، ويوفر ترطيبًا عميقًا ودائمًا.',
    },
    price: 7200,
    imageUrl: 'https://picsum.photos/seed/102/600/600',
    imageHint: 'serum dropper',
    category: 'Ferments',
    ingredients: { en: ['Inonotus Obliquus (Chaga) Ferment Filtrate', 'Propanediol', '1,2-Hexanediol'], ar: ['مرشح تخمير فطر الشاجا', 'بروبانيديول', '1,2-هيكسانيديول'] },
    application: { en: 'Gently pat onto the face and neck after cleansing.', ar: 'ربتي بلطف على الوجه والرقبة بعد التنظيف.' },
    benefits: { en: ['Strengthens Skin Barrier', 'Deep Hydration', 'Improves Radiance'], ar: ['يقوي حاجز البشرة', 'ترطيب عميق', 'يحسن الإشراق'] },
    type: 'b2b',
  },
  {
    id: 'prod_006',
    name: { en: 'Lion\'s Mane Probiotic', ar: 'بروبيوتيك عرف الأسد' },
    slug: 'lions-mane-probiotic',
    description: {
      en: 'A cutting-edge ferment featuring Lion\'s Mane mushroom and lactobacillus. This active supports a healthy skin microbiome, calms irritation and redness, and helps improve the skin\'s resilience against environmental stressors.',
      ar: 'تخمير متطور يضم فطر عرف الأسد والعصيات اللبنية. يدعم هذا العنصر النشط ميكروبيوم بشرة صحي، ويهدئ التهيج والاحمرار، ويساعد على تحسين مرونة البشرة ضد الضغوطات البيئية.',
    },
    price: 8200,
    imageUrl: 'https://picsum.photos/seed/106/600/600',
    imageHint: 'lab equipment',
    category: 'Ferments',
    ingredients: { en: ['Hericium Erinaceus (Lion\'s Mane) Extract', 'Lactobacillus Ferment Lysate', 'Arginine'], ar: ['مستخلص فطر عرف الأسد', 'مرشح تخمير العصيات اللبنية', 'أرجينين'] },
    application: { en: 'Ideal for sensitive or compromised skin. Apply as a calming base layer.', ar: 'مثالي للبشرة الحساسة أو المتضررة. يوضع كطبقة أساسية مهدئة.' },
    benefits: { en: ['Calms Irritation', 'Supports Microbiome', 'Improves Resilience'], ar: ['يهدئ التهيج', 'يدعم الميكروبيوم', 'يحسن المرونة'] },
    type: 'b2b',
  },
  {
    id: 'prod_013',
    name: { en: 'Kombucha Black Tea Ferment', ar: 'تخمير الشاي الأسود (كومبوتشا)' },
    slug: 'kombucha-black-tea-ferment',
    description: {
      en: 'A naturally carbonated ferment that brings a gentle exfoliating effect to the skin. It smooths rough texture and clarifies pores for a crystal-clear complexion.',
      ar: 'مخمر مكربن بشكل طبيعي يجلب تأثيراً مقشراً لطيفاً للبشرة. ينعم الملمس الخشن ويصفي المسام لبشرة صافية كالبلور.',
    },
    price: 6500,
    imageUrl: 'https://picsum.photos/seed/113/600/600',
    imageHint: 'fermenting jar',
    category: 'Ferments',
    ingredients: { en: ['Saccharomyces/Xylinum/Black Tea Ferment', 'Glycerin'], ar: ['تخمير الشاي الأسود', 'غليسرين'] },
    application: { en: 'Apply with a cotton pad to gently sweep away dead skin cells.', ar: 'يوضع بقطعة قطن لمسح خلايا الجلد الميتة بلطف.' },
    benefits: { en: ['Gentle Exfoliation', 'Clarifies Pores'], ar: ['تقشير لطيف', 'يصفي المسام'] },
    type: 'b2b',
  },
  {
    id: 'prod_014',
    name: { en: 'Rice Bran Ferment Filtrate', ar: 'مرشح تخمير نخالة الأرز' },
    slug: 'rice-bran-ferment-filtrate',
    description: {
      en: 'An ancient secret updated with modern fermentation. It is packed with amino acids and vitamins to deeply nourish and restore the skin\'s natural barrier.',
      ar: 'سر قديم محدث بالتخمير الحديث. مليء بالأحماض الأمينية والفيتامينات لتغذية عميقة واستعادة الحاجز الطبيعي للبشرة.',
    },
    price: 7000,
    imageUrl: 'https://picsum.photos/seed/114/600/600',
    imageHint: 'white liquid in bottle',
    category: 'Ferments',
    ingredients: { en: ['Rice Ferment Filtrate', 'Lactic Acid'], ar: ['مرشح تخمير الأرز', 'حمض اللاكتيك'] },
    application: { en: 'Use as a toner essence immediately after washing the face.', ar: 'يستخدم كخلاصة التونر مباشرة بعد غسل الوجه.' },
    benefits: { en: ['Nourishing', 'Restores Barrier'], ar: ['مغذي', 'يستعيد الحاجز'] },
    type: 'b2b',
  },

  // ---------------- OILS ----------------
  {
    id: 'prod_003',
    name: { en: 'Cordyceps Infused Squalane', ar: 'سكوالين مشبع بالكورديسيبس' },
    slug: 'cordyceps-infused-squalane',
    description: {
      en: 'A luxurious, lightweight facial oil combining the energizing properties of Cordyceps mushroom with the emollient benefits of plant-derived squalane. It boosts cellular energy, improves skin elasticity, and locks in moisture without a greasy feel.',
      ar: 'زيت وجه فاخر وخفيف الوزن يجمع بين خصائص فطر الكورديسيبس المنشطة والفوائد المرطبة للسكوالين المشتق من النباتات. يعزز طاقة الخلايا، ويحسن مرونة البشرة، ويحبس الرطوبة دون ملمس دهني.',
    },
    price: 9500,
    imageUrl: 'https://picsum.photos/seed/103/600/600',
    imageHint: 'oil bottle',
    category: 'Oils',
    ingredients: { en: ['Squalane', 'Cordyceps Sinensis Extract', 'Tocopherol (Vitamin E)'], ar: ['سكوالين', 'مستخلص كورديسيبس', 'فيتامين هـ'] },
    application: { en: 'Warm 3-4 drops between palms and press gently onto the face and neck.', ar: 'دفي 3-4 قطرات بين راحتي يديك واضغطي بلطف على الوجه والرقبة.' },
    benefits: { en: ['Boosts Cellular Energy', 'Improves Elasticity', 'Moisturizing'], ar: ['يعزز طاقة الخلايا', 'يحسن المرونة', 'مرطب'] },
    type: 'b2b',
  },
  {
    id: 'prod_015',
    name: { en: 'Argan & Reishi Elixir', ar: 'إكسير الأركان والريشي' },
    slug: 'argan-reishi-elixir',
    description: {
      en: 'Cold-pressed Moroccan Argan oil meets Reishi spore extract. This elixir brings maximum lipid restoration to very dry skin types.',
      ar: 'زيت الأركان المغربي المعصور على البارد يلتقي بمستخلص فطر الريشي. يعيد هذا الإكسير بناء الدهون بشكل أقصى للبشرة الجافة جداً.',
    },
    price: 10500,
    salePrice: 9500,
    imageUrl: 'https://picsum.photos/seed/115/600/600',
    imageHint: 'golden oil drops',
    category: 'Oils',
    ingredients: { en: ['Argania Spinosa Kernel Oil', 'Ganoderma Lucidum Extract'], ar: ['زيت نواة الأركان', 'مستخلص الجانوديرما لوسيدوم'] },
    application: { en: 'Massage gently into skin at night to seal in moisture.', ar: 'دلكيه بلطف على البشرة ليلاً لحبس الرطوبة.' },
    benefits: { en: ['Lipid Restoration', 'Deeply Moisturizing'], ar: ['استعادة الدهون', 'ترطيب عميق'] },
    type: 'b2b',
  },
  {
    id: 'prod_016',
    name: { en: 'Rosehip Mushroom Oil', ar: 'زيت ثمر الورد بالفطر' },
    slug: 'rosehip-mushroom-oil',
    description: {
      en: 'A powerful blend of organic rosehip seed oil and adaptogenic mushroom extracts designed to fade scars and improve skin texture.',
      ar: 'مزيج قوي من زيت بذور ثمر الورد العضوي ومستخلصات الفطر التكيفية المصممة لإخفاء الندبات وتحسين ملمس البشرة.',
    },
    price: 8900,
    imageUrl: 'https://picsum.photos/seed/116/600/600',
    imageHint: 'rosehip seeds and oil',
    category: 'Oils',
    ingredients: { en: ['Rosa Canina Seed Oil', 'Mushroom Extract Blend'], ar: ['زيت بذور روزا كانينا', 'مزيج مستخلص الفطر'] },
    application: { en: 'Apply targetingly to scars or all over for an evening glow.', ar: 'يوضع على الندبات بشكل محدد أو على كامل الوجه لإشراقة مسائية.' },
    benefits: { en: ['Fades Scars', 'Improves Texture'], ar: ['يخفي الندبات', 'يحسن الملمس'] },
    type: 'b2b',
  },

  // ---------------- PEPTIDES ----------------
  {
    id: 'prod_004',
    name: { en: 'Tremella Myco-Peptide', ar: 'ببتيد فطر تريميلا' },
    slug: 'tremella-myco-peptide',
    description: {
      en: 'A breakthrough peptide complex derived from Tremella mushroom. Known for its incredible water-retention capabilities, this active mimics hyaluronic acid to deliver intense hydration while stimulating collagen synthesis for firmer, plumper skin.',
      ar: 'مركب ببتيد مبتكر مشتق من فطر تريميلا. يُعرف بقدراته المذهلة على الاحتفاظ بالماء، وهذا العنصر النشط يحاكي حمض الهيالورونيك لتوفير ترطيب مكثف مع تحفيز الكولاجين لبشرة أكثر تماسكًا وامتلاءً.',
    },
    price: 11000,
    salePrice: 9900,
    imageUrl: 'https://picsum.photos/seed/104/600/600',
    imageHint: 'science glassware',
    category: 'Peptides',
    ingredients: { en: ['Water', 'Glycerin', 'Tremella Fuciformis Polysaccharide', 'Palmitoyl Tripeptide-5'], ar: ['ماء', 'غليسرين', 'عديد السكاريد من تريميلا', 'بالميتويل ثلاثي الببتيد-5'] },
    application: { en: 'Use as a targeted treatment on areas prone to dryness or fine lines.', ar: 'يستخدم كعلاج مستهدف للمناطق المعرضة للجفاف أو الخطوط الدقيقة.' },
    benefits: { en: ['Intense Hydration', 'Collagen Boosting', 'Plumps Skin'], ar: ['ترطيب مكثف', 'يعزز الكولاجين', 'يملأ البشرة'] },
    type: 'b2b',
  },
  {
    id: 'prod_017',
    name: { en: 'Copper Tripeptide-1 Myco', ar: 'ببتيد النحاس الثلاثي الفطري' },
    slug: 'copper-tripeptide-1-myco',
    description: {
      en: 'A revolutionary synthesis of Copper peptides and fungal extracts to accelerate wound healing and drastically reduce the appearance of deep wrinkles.',
      ar: 'توليفة ثورية من ببتيدات النحاس ومستخلصات الفطريات لتسريع التئام الجروح وتقليل ظهور التجاعيد العميقة بشكل كبير.',
    },
    price: 12500,
    imageUrl: 'https://picsum.photos/seed/117/600/600',
    imageHint: 'blue liquid in vial',
    category: 'Peptides',
    ingredients: { en: ['Copper Tripeptide-1', 'Lentinus Edodes Extract'], ar: ['ببتيد النحاس الثلاثي-1', 'مستخلص فطر شيتاكي'] },
    application: { en: 'Apply a small amount to clean skin daily.', ar: 'ضعي كمية صغيرة على بشرة نظيفة يومياً.' },
    benefits: { en: ['Accelerates Healing', 'Reduces Deep Wrinkles'], ar: ['يسرع الشفاء', 'يقلل التجاعيد العميقة'] },
    type: 'b2b',
  },
  {
    id: 'prod_018',
    name: { en: 'Hexapeptide-8 Complex', ar: 'مركب سداسي الببتيد-8' },
    slug: 'hexapeptide-8-complex',
    description: {
      en: 'Dubbed "botox in a bottle," this hexapeptide blend limits muscle movement to prevent the formation of expression lines around the eyes and forehead.',
      ar: 'يُطلق عليه "البوتوكس في زجاجة"، يحد هذا المزيج من حركة العضلات لمنع تكون خطوط التعبير حول العينين والجبهة.',
    },
    price: 13000,
    imageUrl: 'https://picsum.photos/seed/118/600/600',
    imageHint: 'syringe and vial',
    category: 'Peptides',
    ingredients: { en: ['Acetyl Hexapeptide-8', 'Water', 'Phenoxyethanol'], ar: ['أسيتيل هيكساببتيد-8', 'ماء', 'فينوكسي إيثانول'] },
    application: { en: 'Dab directly onto expression lines twice a day.', ar: 'ربتي مباشرة على خطوط التعبير مرتين في اليوم.' },
    benefits: { en: ['Prevents Expression Lines', 'Smoothing'], ar: ['يمنع خطوط التعبير', 'تنعيم'] },
    type: 'b2b',
  },

  // ---------------- GROW KITS ----------------
  {
    id: 'prod_007',
    name: { en: 'Oyster Mushroom Grow Kit', ar: 'علبة زراعة فطر المحار' },
    slug: 'oyster-mushroom-grow-kit',
    description: {
      en: 'Everything you need to grow delicious Oyster mushrooms at home. Simple, fun, and rewarding. Harvest your first crop in as little as 10 days.',
      ar: 'كل ما تحتاجه لزراعة فطر المحار اللذيذ في المنزل. بسيطة وممتعة ومجزية. احصد محصولك الأول في أقل من 10 أيام.',
    },
    price: 2800,
    salePrice: 2500,
    imageUrl: 'https://picsum.photos/seed/201/600/600',
    imageHint: 'mushroom grow kit',
    category: 'Grow Kits',
    ingredients: { en: ['Organic Substrate', 'Oyster Mushroom Mycelium'], ar: ['ركيزة عضوية', 'غزل فطري لفطر المحار'] },
    application: { en: 'Mist with water daily and watch them grow.', ar: 'رش بالماء يوميًا وشاهدهم ينمون.' },
    benefits: { en: ['Easy to Grow', 'Fresh, Organic Food', 'Educational'], ar: ['سهل الزراعة', 'طعام عضوي طازج', 'تعليمي'] },
    type: 'b2c',
  },
  {
    id: 'prod_008',
    name: { en: 'Lion\'s Mane Grow Kit', ar: 'علبة زراعة فطر عرف الأسد' },
    slug: 'lions-mane-grow-kit',
    description: {
      en: 'Cultivate your own Lion\'s Mane mushrooms, a unique gourmet and medicinal fungus. This kit makes it easy to grow these fascinating "pom-pom" mushrooms in your kitchen.',
      ar: 'ازرع فطر عرف الأسد الخاص بك، وهو فطر فريد من نوعه للذواقة والطب. تجعل هذه المجموعة من السهل زراعة هذه الفطريات الرائعة "الكرية" في مطبخك.',
    },
    price: 3200,
    imageUrl: 'https://picsum.photos/seed/202/600/600',
    imageHint: 'gourmet mushrooms',
    category: 'Grow Kits',
    ingredients: { en: ['Organic Substrate', 'Lion\'s Mane Mycelium'], ar: ['ركيزة عضوية', 'غزل فطري لفطر عرف الأسد'] },
    application: { en: 'Follow the included instructions. Requires daily misting.', ar: 'اتبع التعليمات المرفقة. يتطلب رشًا يوميًا.' },
    benefits: { en: ['Gourmet ingredient at home', 'Supports cognitive health'], ar: ['مكون للذواقة في المنزل', 'يدعم الصحة المعرفية'] },
    type: 'b2c',
  },
  {
    id: 'prod_019',
    name: { en: 'Pink Oyster Grow Kit', ar: 'علبة زراعة المحار الوردي' },
    slug: 'pink-oyster-grow-kit',
    description: {
      en: 'Grow vibrant, beautiful pink oyster mushrooms right on your kitchen counter. They grow incredibly fast and have a delicious savory flavor.',
      ar: 'ازرع فطر المحار الوردي النابض بالحياة والجميل على منضدة مطبخك. ينمو بسرعة مذهلة ويتمتع بنكهة مالحة ولذيذة.',
    },
    price: 3000,
    imageUrl: 'https://picsum.photos/seed/219/600/600',
    imageHint: 'pink mushrooms',
    category: 'Grow Kits',
    ingredients: { en: ['Organic Substrate', 'Pink Oyster Mycelium'], ar: ['ركيزة عضوية', 'غزل فطري للمحار الوردي'] },
    application: { en: 'Open the box, spray with water twice a day.', ar: 'افتح العلبة، ورشها بالماء مرتين يومياً.' },
    benefits: { en: ['Beautiful Colors', 'Fast Growing', 'Tasty'], ar: ['ألوان جميلة', 'نمو سريع', 'لذيذ'] },
    type: 'b2c',
  },
  {
    id: 'prod_020',
    name: { en: 'Enoki Mushroom Kit', ar: 'علبة زراعة الإينوكي' },
    slug: 'enoki-mushroom-kit',
    description: {
      en: 'A perfect kit to grow the delicate and crunchy Enoki mushrooms. Often used in soups and salads, they are a staple in Asian cuisine.',
      ar: 'مجموعة مثالية لزراعة فطر الإينوكي الرقيق والمقرمش. يستخدم غالباً في الشوربات والسلطات، ويعتبر عنصراً أساسياً في المطبخ الآسيوي.',
    },
    price: 2600,
    salePrice: 2200,
    imageUrl: 'https://picsum.photos/seed/220/600/600',
    imageHint: 'white thin mushrooms',
    category: 'Grow Kits',
    ingredients: { en: ['Sterilized Substrate', 'Enoki Mycelium'], ar: ['ركيزة معقمة', 'غزل فطري للإينوكي'] },
    application: { en: 'Keep in a cool, dark place and mist lightly.', ar: 'يحفظ في مكان بارد ومظلم ويرش برفق.' },
    benefits: { en: ['Crunchy Texture', 'Great for Soups'], ar: ['قوام مقرمش', 'رائع للشوربات'] },
    type: 'b2c',
  },

  // ---------------- LAB SUPPLIES ----------------
  {
    id: 'prod_009',
    name: { en: 'Sterilized Petri Dishes (20 Pack)', ar: 'أطباق بتري معقمة (20 قطعة)' },
    slug: 'sterilized-petri-dishes',
    description: {
      en: 'A pack of 20 pre-sterilized, 100mm x 15mm polystyrene petri dishes, perfect for mycology culture work. Vented for air exchange while preventing contamination.',
      ar: 'عبوة من 20 طبق بتري من البوليسترين معقم مسبقًا، مقاس 100 مم × 15 مم، مثالية لأعمال زراعة الفطريات. مزودة بفتحات تهوية لتبادل الهواء مع منع التلوث.',
    },
    price: 2200,
    imageUrl: 'https://picsum.photos/seed/203/600/600',
    imageHint: 'petri dish stack',
    category: 'Lab Supplies',
    ingredients: { en: ['Polystyrene'], ar: ['بوليسترين'] },
    application: { en: 'Use for agar work, culture isolation, and cloning.', ar: 'تستخدم لأعمال الأجار، وعزل المزارع، والاستنساخ.' },
    benefits: { en: ['Ready to use', 'Durable and clear', 'Standard size'], ar: ['جاهز للاستخدام', 'متين وواضح', 'حجم قياسي'] },
    type: 'b2c',
  },
  {
    id: 'prod_010',
    name: { en: 'Liquid Culture Vials (10 Pack)', ar: 'قوارير المزرعة السائلة (10 قطع)' },
    slug: 'liquid-culture-vials',
    description: {
      en: 'Ten glass vials with self-healing injection ports and sterile filters, pre-filled with a nutrient-rich liquid culture medium. Ideal for expanding and storing your mushroom cultures.',
      ar: 'عشر قوارير زجاجية مع منافذ حقن ذاتية الشفاء ومرشحات معقمة، مملوءة مسبقًا بوسط مزرعة سائلة غني بالمغذيات. مثالية لتوسيع وتخزين مزارع الفطر.',
    },
    price: 4500,
    imageUrl: 'https://picsum.photos/seed/204/600/600',
    imageHint: 'lab vials',
    category: 'Lab Supplies',
    ingredients: { en: ['Glass Vials', 'Nutrient Broth', 'Silicone Ports'], ar: ['قوارير زجاجية', 'مرق مغذي', 'منافذ سيليكون'] },
    application: { en: 'Inject your spore solution or culture into the vial and incubate.', ar: 'احقن محلول الأبواغ أو المزرعة في القارورة وقم بالحضانة.' },
    benefits: { en: ['Accelerates colonization', 'Long-term storage', 'Easy to use'], ar: ['يسرع الاستعمار', 'تخزين طويل المدى', 'سهل الاستخدام'] },
    type: 'b2c',
  },
  {
    id: 'prod_021',
    name: { en: 'Agar Powder (500g)', ar: 'مسحوق الأجار (500 جم)' },
    slug: 'agar-powder-500g',
    description: {
      en: 'Premium laboratory-grade agar powder for creating solid culture media. Perfect clarity and ideal gel strength for all mycology applications.',
      ar: 'مسحوق أجار ممتاز من الدرجة المختبرية لإنشاء أوساط زراعة صلبة. وضوح مثالي وقوة هلامية مثالية لجميع تطبيقات الفطريات.',
    },
    price: 5500,
    imageUrl: 'https://picsum.photos/seed/221/600/600',
    imageHint: 'white powder in jar',
    category: 'Lab Supplies',
    ingredients: { en: ['100% Pure Agar-Agar'], ar: ['أجار-أجار نقي 100%'] },
    application: { en: 'Mix with water and nutrients, boil, and pour into petri dishes.', ar: 'امزجه بالماء والمغذيات، اغليه، وصبه في أطباق بتري.' },
    benefits: { en: ['High Clarity', 'Strong Gel', 'Lab Grade'], ar: ['وضوح عالي', 'هلام قوي', 'درجة مختبرية'] },
    type: 'b2c',
  },
  {
    id: 'prod_022',
    name: { en: 'Micropore Tape (6 Rolls)', ar: 'شريط لاصق مسامي (6 بكرات)' },
    slug: 'micropore-tape-6-rolls',
    description: {
      en: 'Breathable surgical tape used for covering inoculation holes on grain jars and fruiting blocks. Allows gas exchange while keeping out contaminants.',
      ar: 'شريط جراحي قابل للتنفس يستخدم لتغطية ثقوب التلقيح على برطمانات الحبوب وكتل الإثمار. يسمح بتبادل الغازات مع منع دخول الملوثات.',
    },
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/222/600/600',
    imageHint: 'rolls of white tape',
    category: 'Lab Supplies',
    ingredients: { en: ['Non-woven Rayon', 'Hypoallergenic Adhesive'], ar: ['حرير صناعي غير منسوج', 'لاصق مضاد للحساسية'] },
    application: { en: 'Apply over holes after inoculation.', ar: 'يوضع فوق الثقوب بعد التلقيح.' },
    benefits: { en: ['Breathable', 'Blocks Contaminants', 'Gentle'], ar: ['قابل للتنفس', 'يمنع الملوثات', 'لطيف'] },
    type: 'b2c',
  },
];
